name: Go Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Test
    runs-on: macOS-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Run Tests
      run: make test_unit_race
